#!/usr/bin/env bash

if [ "$#" -le 1 ]; then
echo "Requires branch name passed as argument"
fi
nixL=~/nixstuff
confi=~/.config
cp /etc/nixos/configuration.nix $nixL/
cp -r ~/.shells/* $nixL/shells/
cp -r $confi/awesome/* $confi/kitty/* $nixL/.config/

git add .
read reason
git commit -m $reason 
git push 
