#!/usr/bin/env bash 

h=~/

cp /etc/nixos/configuration.nix $h/conf.bak
sudo nixos-generate-config
cd $h/nixstuff
sudo cp configuration.nix /etc/nixos/configuration.nix
cp -r .config/* ../.config/
sudo nixos-rebuild switch
home-manager switch
