#!/usr/bin/env bash

nixL=~/nixstuff
confi=~/.config
cp /etc/nixos/configuration.nix $nixL/
cp -r ~/.shells/* $nixL/shells/
cp -r $confi/awesome $nixL/.config/
cp -r $confi/home-manager $nixL/.config/
git add .
echo "Reason for commit: "
read reason
echo "Branch: "
read branch
git commit -m "$reason" 
git push origin $branch
